/*
 * This file is generated by jOOQ.
*/
package fr.mazerty.shika.torii.dao.jooq.tables.records;


import fr.mazerty.shika.torii.dao.jooq.tables.TUserApplication;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserApplicationRecord extends UpdatableRecordImpl<TUserApplicationRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 532918274;

    /**
     * Setter for <code>torii.t_user_application.user_fk</code>.
     */
    public void setUserFk(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>torii.t_user_application.user_fk</code>.
     */
    public Integer getUserFk() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>torii.t_user_application.application_fk</code>.
     */
    public void setApplicationFk(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>torii.t_user_application.application_fk</code>.
     */
    public Integer getApplicationFk() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TUserApplication.T_USER_APPLICATION.USER_FK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TUserApplication.T_USER_APPLICATION.APPLICATION_FK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getApplicationFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserApplicationRecord value1(Integer value) {
        setUserFk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserApplicationRecord value2(Integer value) {
        setApplicationFk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserApplicationRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TUserApplicationRecord
     */
    public TUserApplicationRecord() {
        super(TUserApplication.T_USER_APPLICATION);
    }

    /**
     * Create a detached, initialised TUserApplicationRecord
     */
    public TUserApplicationRecord(Integer userFk, Integer applicationFk) {
        super(TUserApplication.T_USER_APPLICATION);

        set(0, userFk);
        set(1, applicationFk);
    }
}
