/*
 * This file is generated by jOOQ.
*/
package fr.mazerty.shika.torii.dao.jooq.tables;


import fr.mazerty.shika.torii.dao.jooq.Keys;
import fr.mazerty.shika.torii.dao.jooq.Torii;
import fr.mazerty.shika.torii.dao.jooq.tables.records.TUserApplicationRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserApplication extends TableImpl<TUserApplicationRecord> {

    private static final long serialVersionUID = 897476220;

    /**
     * The reference instance of <code>torii.t_user_application</code>
     */
    public static final TUserApplication T_USER_APPLICATION = new TUserApplication();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TUserApplicationRecord> getRecordType() {
        return TUserApplicationRecord.class;
    }

    /**
     * The column <code>torii.t_user_application.user_fk</code>.
     */
    public final TableField<TUserApplicationRecord, Integer> USER_FK = createField("user_fk", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>torii.t_user_application.application_fk</code>.
     */
    public final TableField<TUserApplicationRecord, Integer> APPLICATION_FK = createField("application_fk", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>torii.t_user_application</code> table reference
     */
    public TUserApplication() {
        this("t_user_application", null);
    }

    /**
     * Create an aliased <code>torii.t_user_application</code> table reference
     */
    public TUserApplication(String alias) {
        this(alias, T_USER_APPLICATION);
    }

    private TUserApplication(String alias, Table<TUserApplicationRecord> aliased) {
        this(alias, aliased, null);
    }

    private TUserApplication(String alias, Table<TUserApplicationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Torii.TORII;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TUserApplicationRecord> getPrimaryKey() {
        return Keys.T_USER_APPLICATION_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TUserApplicationRecord>> getKeys() {
        return Arrays.<UniqueKey<TUserApplicationRecord>>asList(Keys.T_USER_APPLICATION_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TUserApplicationRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TUserApplicationRecord, ?>>asList(Keys.T_USER_APPLICATION__T_USER_APPLICATION_USER_FK_FKEY, Keys.T_USER_APPLICATION__T_USER_APPLICATION_APPLICATION_FK_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserApplication as(String alias) {
        return new TUserApplication(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TUserApplication rename(String name) {
        return new TUserApplication(name, null);
    }
}
